# Generated by Django 5.2 on 2025-04-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
